- name: Install pip
  become: true
  apt:
    name: python3-pip
    state: present

- name: Add user to docker group
  ansible.builtin.user:
    name: "{{ ansible_user }}"
    groups: docker

- include_tasks: install_docker.yml
- include_tasks: install_compose.yml